// import React, { useState } from "react";

// // קומפוננטת Ai שמכילה את זרימת העבודה של n8n
// const Ai = () => {
//   // מצב לדמו של הודעת צ'אט וקישור התמונה שנוצרה
//   const [chatMessage, setChatMessage] = useState("");
//   const [imageUrl, setImageUrl] = useState("");

//   // פונקציה לדמו של שליחת הודעת צ'אט ל-n8n
//   const handleSendMessage = async () => {
//     try {
//       // כאן היית שולח את הנתונים ל-n8n webhook
//       // לדוגמה:
//       const response = await fetch(
//         "https://YOUR_N8N_WEBHOOK_URL/d4d986de-ac0f-47f1-b225-ac1ef3237d9d",
//         {
//           method: "POST",
//           headers: { "Content-Type": "application/json" },
//           body: JSON.stringify({ message: chatMessage }),
//         }
//       );

//       const data = await response.json();

//       // הנחה: n8n מחזיר URL של התמונה שנוצרה
//       setImageUrl(data.imageUrl || "");
//     } catch (error) {
//       console.error("Error generating image:", error);
//     }
//   };

//   return (
//     <div>
//       <h2>AI Image Generator</h2>
//       <input
//         type="text"
//         placeholder="Type your message..."
//         value={chatMessage}
//         onChange={(e) => setChatMessage(e.target.value)}
//       />
//       <button onClick={handleSendMessage}>Send</button>

//       {imageUrl && (
//         <div>
//           <h3>Generated Image:</h3>
//           <img src={imageUrl} alt="Generated by AI" />
//         </div>
//       )}
//     </div>
//   );
// };

// export default Ai;
// App.tsx
import { useEffect } from 'react';
import '@n8n/chat/style.css';
import { createChat } from '@n8n/chat';

export const Ai = () => {
	useEffect(() => {
		createChat({
			webhookUrl: 'https://n8n.srv1251456.hstgr.cloud/webhook/d4d986de-ac0f-47f1-b225-ac1ef3237d9d/chat'
		});
	}, []);

	return (<div></div>);
};